name: text_scroller
description: A highly customizable text scrolling widget. You can customize all the aspects.
version: 0.0.4
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
